app = "john-mahjong"
primary_region = "fra"

[build]
  image = "john-mahjong"

[processes]
  app = "python bot.py"

[services]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
